"""Change contact field to String

Revision ID: 64363f79c880
Revises: 20bd21d2ae1d
Create Date: 2024-12-14 00:32:46.816824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64363f79c880'
down_revision = '20bd21d2ae1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('contact',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('contact',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
